### ISSUE TITLE
Add basic analytics to the website

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-project.github.io#9]
## Why
As we're having the opportunity to promote Pixelated more on conferences and social media, it's important to understand what kinds of actions brings more users to the website - and, from there, to our repositories.

## Open questions
- What metrics do we want to track?
- What are the alternatives to google analytics we want to use?

## Alternatives
- Piwik: http://piwik.org/faq/new-to-piwik/
- Open Web Analytics: http://www.openwebanalytics.com/

## Tasks

- [x] Install piwik on master1
- [x] Gather logs from nginx into piwik
- [ ] Include statement about analytics logging on website

**Comment by kaeff** [comment]
I've been trying out piwik on a throwaway heroku installation and it looks like a good fit. I'd need some guidance around setting up a host for piwik on our infrastructure. Leaving this blocked until then.

**Comment by kaeff** [comment]
as suggested by @varac and @cz8s , now installing piwik manually on master1 in the log-parsing mode. that way we don't have to use JS to gather metrics & its less revealing. we should mention what we track on the website nevertheless.

**Comment by kaeff** [comment]
> I saw it working
-- @cz8s

**Comment by cz8s** [comment]
True
-- 
Sent from my phone. Please excuse my brevity.
